export const menus = [
  {
    title: 'Mojito',
    children: [
      'useActiveBids',
      'useCollection',
      'useCollectionItemBidsList',
      'useCollectionItemCurrentBids',
      'useCollectionItemRemainingCount',
      'useCollectionItemsCurrentBids',
      'useCollectionLotsIdList',
      'useCollectionSlug',
      'useFavoriteItems',
      'useInvoiceDownload',
      'useInvoices',
      'useLazyMojitoOneLot',
      'useMarketplaceCollectionsSlugWithItemsId',
      'useMojitoItem',
      'useMojitoMutation',
      'useMojitoWallets',
      'useOrganization',
      'usePlaceBidMutation',
      'useProfile',
      'useServerTime',
    ],
  },
  {
    title: 'Contentful',
    children: [
      'useContentfulAuctionsSlugList',
      'useContentfulAuthors',
      'useContentfulCollectors',
      'useContentfulLots',
      'useContentfulShortLots',
    ],
  },
  {
    title: 'Internal',
    children: ['useContentfulFactory', 'useMojitoFactory'],
  },
];
