export const menus = [
  {
    title: 'Advanced',
    children: [
      'useActiveBids',
      'useCollection',
      'useCollectionItemBidsList',
      'useCollectionItemCurrentBids',
      'useCollectionItemRemainingCount',
      'useCollectionItemsCurrentBids',
      'useCollectionLotsIdList',
      'useCollectionSlug',
      'useContentfulAuctionsSlugList',
      'useContentfulAuthors',
      'useContentfulCollectors',
      'useContentfulFactory',
      'useContentfulLots',
      'useContentfulShortLots',
      'useFavorites',
      'useInvoiceDownload',
      'useInvoices',
      'useLazyMojitoOneLot',
      'useMarketplaceCollectionsSlugWithItemsId',
      'useMojitoFactory',
      'useMojitoItem',
      'useMojitoMutationFactory',
      'useMojitoWallets',
      'useOrganization',
      'usePlaceBidMutation',
      'useProfile',
      'useServerTime',
    ],
  },
];
