name: 'Code Style & Quality'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --frozen-lockfile
        working-directory: ./packages/hooks
      - run: yarn install --frozen-lockfile
      - run: yarn lint
  build:
    name: Build
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --frozen-lockfile
        working-directory: ./packages/hooks
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: test -e ./packages/hooks/es/index.js
      - run: test -e ./packages/hooks/lib/index.js

  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: '14.x'
  #         registry-url: 'https://registry.npmjs.org'
  #     - run: yarn install --frozen-lockfile
  #       working-directory: ./packages/hooks
  #     - run: yarn test
  #       working-directory: ./packages/hooks
